name: 'Docker Action Testing'
description: 'testing docker actions'
runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: '/pre-entrypoint.sh'
  entrypoint: '/entrypoint.sh'
  post-entrypoint: '/post-entrypoint.sh'
